### ISSUE TITLE
Diversity for handicaped or non-english readers too?

### ISSUE THREAD

**Issue by Hanmac** [symfony/diversity#20]
i think the whole "diversity" thing is just vitue signaling if it isn't done for all of them.

last year i read on the symfony blog that the support for non english pages got dropped because of not enough support. [there](https://symfony.com/blog/discontinuing-the-community-translations)
now there is this thing with forcing more "diversity". Now i ask you are non-english reader not diverse enough for you?

or what about handicaped persons? is your website optimised for colorblind or for speech / screenreaders?

if your diversity is only for previleged people, then your diversity is worth nothing

**Comment by iltar** [comment]
> now there is this thing with forcing more "diversity". Now i ask you are non-english reader not diverse enough for you?

PHP is based off English and so is the whole Symfony codebase, So it kind of makes sense that in order to use Symfony, you have to have a basic knowledge of English. On top of that, maintaining docs, restructuring them and keeping them up-to-date is already hard enough in 1 language. If I add a new feature, I'd like to add the documentation as well, I can't do this in multiple languages. This means that for every single change, for every language, it increases the complexity of contributing or fixing issues in the docs. 

I'm not saying it's impossible, but imo it's not worth the extra effort as English is already required for PHP and Symfony. If you don't speak English, you'll miss out probably 90% of the online resources either way. 

The other option would be a translation service, but this is not something Symfony has to provide. This is a service that everyone who doesn't speak English can use and the quality of those translations become better with each iteration.

> or what about handicaped persons? is your website optimised for colorblind or for speech / screenreaders?

I have no experience with that, but this is something that should not be too hard. I'm curious how many blind people are actually programming and how they do it though. I've never thought about this before.

**Comment by Hanmac** [comment]
i did this ticket to show possible double standards with something like diversity

its one thing to say that you are so diverse, but drop the support the moment its more work then just saying (for example the blog translations)
"saying is good, doing is better"
you guys need to keep this in mind if are giving divserse support to different groups, and then thinking why not to others too


with diversity you also need to becareful about becoming what you fight against:
if you have a diverse team is good.
if you are only hire a black guy/woman because you need one in your team to get more diverse points,
then its bad because with that you would be a racist and not much better that what you are trying to fight against with the diversity

**Comment by dbu** [comment]
this issue mixes two (mostly) unrelated topics, handicap and language. (the relation being that if you improve the content for people with handicaps in understanding complex texts, you at the same time make it easier for people with a limited grasp of english).

> language

I agree with @iltar that the effort for maintaining fully translated documentation is enormous. It was abandoned for Symfony because the documentation drifted out of sync, and outdated/incorrect documentation is worse than documentation in a language i am less familiar with.

I would not say that you can't do PHP if you don't know english. The php.net page is translated into several languages, and there are lots of books and whatnot in various languages. I can see the need, but i can't see the resources. This is not about change in the community, but about a very massive continous financial investment...

There are conferences encouraging talks in the local language (symfony live for example). There are communities in various countries that probably also produce local languages content. Afaik sensiolabs is encouraging those communities. Is there more that could be done on the symfony.com website? Making local communities more visible might help - although for readers who really struggle with english, i doubt that they would find those communities even if it was more linked. Also, i expect this to work the other way round, people connecting with a local community and then discovering Symfony through that community.

> handicaps

i don't know if an accessibility check has been done for symfony.com, but that definitely would be a good idea.

* there are automated tools for topics like accessibility for colorblind people. => #21
* a full accessibility review (screen readers et al.) is best done by a specialized agency. this would probably need somebody who wants to sponsor that.

**Comment by lsmith77** [comment]
First up, yes when we talk about diversity, we also mean getting more people from around the world involved and I do agree that language is likely a barrier.

I think maybe a starting point is to translate some parts, like the getting started guide.
Furthermore there are already support channels for different native languages on our slack, maybe we should advertise this more and invite people to start channels in their native language?
Also I do hope that we can have more regional conferences that at least partially feature talks in the native language.

**Comment by fabpot** [comment]
Regarding the translations on symfony.com: we dropped them because they were not maintained. Obsolete docs are worse than no docs at all. Having the docs translated in a language requires at least one full time person. The community cannot afford it. That being said, translations do not need to be managed by the Symfony core team itself. Having groups of people working on translating the docs in other languages would be wonderful. But the reality is that the effort is gigantic. Even for a community as big as Symfony.

That's very different from things we can do within our financial constraints (free time given by a large number of people).

**Comment by lsmith77** [comment]
for the record here is the issue where it was decided to drop the translations:
https://github.com/symfony/symfony-docs/issues/4078

note the two translations that existed at the time don’t exist anymore.

@javiereguiluz confirmed to me that we have `class=“notranslate”` in the docs which should make google translate somewhat viable.

**Comment by lsmith77** [comment]
continuing the topic if translations here https://github.com/symfony/diversity/issues/51

in terms of a11y on the website we have monthly reports automated via a11ym.com that we setup as part of https://github.com/symfony/diversity/issues/21 .. there are still a number of open errors/warnings/notices but they are getting reduced. if you want access to these reports to help out, please let me know and I will add anyone motivated.
