### ISSUE TITLE
Define groups to support and to invite

### ISSUE THREAD

**Issue by ElectricMaxxx** [symfony/diversity#26]
We are talking about that diversity theme, but do we really know which parts of our real live community need special support? (or even want to have it).
From the first view we are talking about women. But what about

* disabled persons
* family guys and womens
* poor people with hard ways to get into our community
* even simple introverted people

The last group is a task we do have in our daily bussiness also, we have to integrate them and try to push them to give some feedback when trying to elaborate havy domains or simply doing some kind of retrospective. 

I am from the second group (maybe also partly from first in the next years). And i can say, that taking part in the community is quite hard, when having a family. Kids and wife are awsome and i am the happiest man alive, cause i have them. But my freetime moves into the night or into smal ranges while driving train or something else. So that is a difference to a single young man. To integrate that group or give them better chance would also pay on the try to get women into the community.

what do you think?

**Comment by sstok** [comment]
I think the biggest take-on is identifying the actual problems these groups face when contributing/trying to contribute. With woman it's mainly sexism, representation (the former SensioConnect avatar for example or using Guys which mostly targets men), not being taken serious because of there sex/gender identity.

With disabled people it's more challenging as there are so many forms of this, and luckily there some initiatives to improve this (including the recent ongoing improvements to the Form component) 👍.

One thing I wondered about is the color usage for Issue labels 😋 is something we may need to look at?

> And i can say, that taking part in the community is quite hard, when having a family. Kids and wife are awsome and i am the happiest man alive, cause i have them. But my freetime moves into the night or into smal ranges while driving train or something else. So that is a difference to a single young man. To integrate that group or give them better chance would also pay on the try to get women into the community.

I wonder what can be done concretely to improve this. We are already working remotely, there are no time constraints, and open source development has always been a best effort game 🤔 

> even simple introverted people

I think this can easily be listed under most newcomers, we (as a community and not just one well known person 😉 ) are already trying to be more friendly to encouraging to newcomers and helping people who struggle with this. Maybe we can look/evaluate what can be done to further improve this, especially for people who struggle more with this then others. 

_And to be clear a mental illness is not fixed by being kind or encouraging, problems like these can be very deep and despite kindness, understanding and proof they are actually talented it will not penetrate through as there bigger issue at hand. It's more a patch for a bigger wound._ And I speak from a personal past experience.

**Comment by sstok** [comment]
Related to #28 with some good tips 👍 (For some reason I forgetting there is a world outside the internet 🙈 conferences an all).

**Comment by stof** [comment]
> One thing I wondered about is the color usage for Issue labels yum is this something we may need to look at?

Labels always have a text, in addition to colors. Not being able to distinguish the color itself does not block understanding the meaning of the label.
So the main issue with the colors would be to ensure that contrast is good. I know github made some changes to label colors a few weeks back precisely to address this.

**Comment by Mx-Glitter** [comment]
A point to keep in mind with surveys is they show the current demographics of the community, but they won't show people who would have like to come in the community and couldn't. It's a very good tool to see where our community is biased compared to general population demographics so that we should act on it.
If we only focus on parts of our current community that need special support, we will miss absent or underrepresented groups where we need to improve.

**Comment by lsmith77** [comment]
absolutely agreed that we need to keep an eye for all forms of discrimination and aspects of diversity. we should work on the linked tickets that have actionable items to work on.
