### ISSUE TITLE
Symfony weekly News 

### ISSUE THREAD

**Issue by zairigimad** [symfony/diversity#29]
I saw a weekly vlog concept that shows what's new in AWS, I think the same concept with Symfony will be a good idea to get the developer's attention. what do you think? 

refernece : https://acloud.guru/series/aws-this-week

**Comment by javiereguiluz** [comment]
@zairigimad without considering if this is a good idea or not, I'm sorry to say that we don't have the resources to do that. Anything audiovisual takes a huge amount of time to do it right.

What we can do is to keep publishing a "A week of Symfony" posts (https://symfony.com/blog/category/a-week-of-symfony) which is a similar idea but it's doable for us because it's a written blog post.

**Comment by lsmith77** [comment]
@javiereguiluz is there anything people within the community could do to support you with the `a week of symfony`?

**Comment by javiereguiluz** [comment]
@lsmith77 thanks ... but I can still manage to create it 😄  (as long as it's a text-based weekly summary and not something audiovisual).

**Comment by lsmith77** [comment]
@zairigimad I will close this ticket as I think it has been answered .. if you disagree, then my apologies and feel free to reopen.
