### ISSUE TITLE
Remove marxist ideas and end the diversity campaign.

### ISSUE THREAD

**Issue by ama-gi** [symfony/diversity#30]
This diversity initiative is build on marxist ideas. Marxist ideas are responsivle for killing millions of people in the 20th century and should therefore be discarded completely. This diversity campaign is also insulting because it claims that the symfony community members are biased by default.

https://en.wikipedia.org/wiki/Mass_killings_under_Communist_regimes

**Comment by javiereguiluz** [comment]
Note: in the Symfony project we're enthusiast of "freedom of speech", so we accept all arguments and discussions that are proposed in a "constructive criticism way". However, if this discussion starts going towards political discussion, we'll lock it immediately. We don't talk about politics in Symfony repos.

-----

Having said that, if your proposal is to end "the diversity initiative" my vote is 👎 . My reasons are that so far it has provided small but nice improvements to Symfony and has made it more inclusive (e.g. https://symfony.com/blog/making-sensiolabs-connect-more-inclusive and https://github.com/symfony/symfony-docs/pull/8645/files). My guess is that it will continue to improve Symfony in positive ways.

**Comment by javiereguiluz** [comment]
@dbu I understand your motivations to close + lock this conversation, but when someone ideas are OK (like ours with the "diversity initiative") we shouldn't be afraid to discuss about them openly. Even with people that wants to remove them. He gave vague arguments to end this initiative ... and I provided better (I hope so!) arguments to keep working on it.

So, if @ama-gi wants to provide objective and non-political reasons to close or change this initiative, please give them. We'll listen to you. Otherwise, we'll need to close this proposal. Thanks!

**Comment by dbu** [comment]
sorry that i closed this too quickly. i see no arguments in this post, only political rambling that has nothing to do with diversity whatsoever.

**Comment by ama-gi** [comment]
This whole repository is about identity politics. There are attempts here to put people into groups (race, disability, gender) but not others and then make changes to pander towards those groups. It is not clear to me what the specific goal is. 

Why pander towards one group and not the other?
Why for example make it easier for refugees to participate but not unattractive people or divorced fathers for example?

How do those groups improve symfony?
What about the intersections of those groups?
Are pull-request not decided on their merit in the future, but by who made them?
Are infractions policed in the future? Like "mislabelling" someone?

**Comment by ama-gi** [comment]
Why judge people by the color of their skin and not the content of their character?

**Comment by javiereguiluz** [comment]
I'm locking the conversation during a few minutes so I can reply to your questions before you keep publishing more questions. Then I'll unlock it.

**Comment by lsmith77** [comment]
We want to create a safe environment for all and to grow out community since with more helping hands, we can achieve more .. so this includes also of course "unattractive people" and "divorced fathers". However at this point I don't see any data points that would indicate that we have created barriers to entry for either of these groups and more specifically that they are underrepresented. That being said, single fathers with children are likely underrepresented due to the fact that open source proportionally relies on "free labor" still (https://www.ashedryden.com/blog/the-ethics-of-unpaid-labor-and-the-oss-community). Do you have data to the contrary of this?

Potentially focussing on refugees is to a large degree about improving ethnic diversity while addressing the logistical reality that its easier to train people if they are in close proximity to potential coaches. However refugees can in turn then help provide content and training to other people in their native language, hence the opportunity to grow our community. Again such logistical or language challenges do not exist with the two example groups you mentioned.

And yes pull requests will still be examined based on their merit, but we aim to be more conscious about how to communicate feedback and how we evaluate merit, ie. a change that will improve things for people with disabilities might may introduce a minor increase in complexity for everyone else, might still get accepted.

As for being "policed", we are still working on the CoC proposal, but the ultimate goal is to help people communicate in a welcoming manner. As such with a project spanning across the world, with ideally people coming from all sorts of life, some level of friction and misunderstandings are unavoidable. The key thing is that we will expect people to listen and learn and to be willing to adjust their behavior.

Generally I think a github issue might not be the best place to discuss this topic. It might make more sense to talk about this on slack.

**Comment by javiereguiluz** [comment]
@ama-gi there are a lot of questions in your comment! Let's answer them:

> Are pull-request not decided on their merit in the future, but by who made them?

THAT WILL NEVER HAPPEN. Issues and pull requests are always judged by their technical merit, not by who created it. Same with reviews: we always give technical reasons when asking for changes and we treat all PRs equally (the only difference is when GitHub shows that a person is a "new contributor" ... we try to be extra careful, patient and kind to those people so they have a better first time experience).

> How do those groups improve symfony?

These groups commonly called "minorities" (women, people of color, etc.) can improve Symfony in the same way the most common group of people (middle aged European white men) improve it today. Our reasoning: if more people contribute to Symfony, we all win. If more "different people" contribute, Symfony could improve even more.

Let me show you a real example. Yesterday I received an issue report in a bundle where a developer with an Arab background told me that or management of RTL languages was wrong and because of that I could fix it (https://github.com/EasyCorp/EasyAdminBundle/pull/2156). I'm an European person, so my culture is LTR. Thank to the diversity of that bundle community, a person from other kind of culture spotted an error and we could fix it ... making that bundle better for lots of people.

But as you can see, we're not saying that RTL people are better or have priority ... we say, "different" people with different backgrounds can report errors or propose features that we can't think of because most of our community is from the same culture and background.

> Why pander towards one group and not the other?

We want to pander towards all kinds of people who are not enough represented in our community today. If 90% of our community were non-white women, then we could target "white men" as one of those minorities. But reality is the opposite and that's why we target other groups of people. But there's nothing wrong with being white, a man or middle-aged. We just say: let's see if we can attract other kind of people and they can help us improve. Maybe they can't! ... but let's try it.

> It is not clear to me what the specific goal is.

Sorry if it's not clear. The goal is: "let's keep improving Symfony" ... the diversity initiative is just one of the ways we can do that.

> Are infractions policed in the future? Like "mislabelling" someone?

Yes. But not based on gender, ethnicity, etc. It's explained here (https://github.com/symfony/symfony-docs/pull/9394) and here (https://github.com/symfony/symfony-docs/pull/9340). The good news is that the rules are objective and applied to everybody in the same way. There will be no exceptions.

**Comment by ama-gi** [comment]
Thank you for the answer javierequiluz.
Good luck with making symfony everything for everyone.
I still think its gross to put people into groups, but I realize not everybody feels this way. I would prefer it If "diversity" was not the goal but improving symfony. The RTL example was great and I totally see the value in that because you made a business case instead of just saying "improve diversity".
Why not scrap the initiative and outline some goals to improve symfony?

Goal 1: Translate Docs to most common languages or languages with the best market potential

No, the translations were scrapped because nobody maintained them...

**Comment by javiereguiluz** [comment]
Yes, it's sad but because of the incredibly activity on Symfony Docs, it's impossible to translate them and keep the translations updated. But there are a lot of community events in non-English languages (https://symfony.com/events/) and some people are translating "New in Symfony" posts into their languages. That's great because Symfony has no language diversity: it was decided that we do everything in English (that's clearly the best decision ever, but it excludes lots of people because most people in the World can't speak English).

In any case, your original proposal was to end this diversity initiative and it's clear from the comments of the maintainers that the proposal is not accepted. That's why we are going to close this issue. But as you can see, we all had a positive and civilized discussion about this topic, so that's great and we thank you for that. 

Lastly, we really hope that when we complete other tasks related to diversity, we can change a bit your opinion about this and see that they can have a positive effect on Symfony. Cheers!

**Comment by ama-gi** [comment]
> That's great because Symfony has no language diversity: it was decided that we do everything in English (that's clearly the best decision ever, but it excludes lots of people because most people in the World can't speak English).

Thank you for highlighting how foolish this whole initiative is. 

Requirements for using symfony:

- Ownership or access to a computer
- Ability to read and understand english
- Internet access
- Intelligence, good memory and attention span

Not required:

- White skin
- Heterosexuality
- Male sex organs

**Comment by lsmith77** [comment]
Your last statement is a very good example of what kind of discussion style should be avoided. The word "foolish" simply makes your statement insulting. It therefore diminishes the value of your feedback but also puts a needless emotion effort on people that you hope to engage with your statement.

As such the diversity initiative, as @javiereguiluz tried to point out already, is to a large degree not about focusing on any particular group but about making it more productive and enjoyable to work on topics in the community. The way you formulated your statement leads to inefficiency because you expect people to invest the effort to look past your insult.

**Comment by ama-gi** [comment]
Its calling a spade a spade, beating around the bush is inefficient. The problem is that oversensitive people feel threatened in their self-esteem If you criticize their ideas. Thats a problem with them, not the messenger of the criticism. I don't think anybody here has any reason to feel insulted by my statement, its only my opinion. The notion that community members should modify their speech so as not to insult an oversensitive person is ridiculous. People that feel personally hurt by criticism can't work together with other people.

**Comment by nicolas-grekas** [comment]
IMHO, "oversensitive persons" is a very subjective concept. It can be just me or any of us on some days. Currently, I know taking part to any discussion needs some sort energy to ignore the self-resonance that some messages create for me. I'd be really thankful for anyone who take some time to think twice about making as peaceful comments as possible, so that at least I know it's not just me who's always having to be "extra-accepting" emotion-triggering comments. So yes, we should all take care of each others when reading *and* when writing.

**Comment by ama-gi** [comment]
I'm not advocating beeing mean or rude, I saying people should be free to be straightforward and honest with their opinion.
There is a difference between comments like this:
https://www.theregister.co.uk/2016/07/11/linus_torvalds_in_sweary_rant_about_punctuation_in_kernel_comments/
and saying: "that a bad/foolish/terrible idea".

**Comment by sstok** [comment]
Oh boy, I hope I am not going to make this to lengthy "again"...

You start by saying "This diversity campaign is also insulting because it claims that the symfony community members are biased by default."

That's making a statement not an opinion. Otherwise you would have said something like 'that in your opinion' the "diversity campaign is insulting". To me this indicates that you are not willing to have a healthy and proper discussion about this topic? and believe me I can go ranting about things that bother me, for days!

But there is one thing I need to keep in mind, if I directly discard someone's opinions and beliefs or start making statements rather then clearly indicating that these are my opinions and I _am willing to change my mind on these subjects_ I can almost automatically expect the other party to have no respect for me neither. Why would they? I am not respecting them, so what reason would they have to respect me. They don't have to agree with me, nor am I expecting them to agree with me. **I am merely expecting of them to respect me as I am respecting them.**

And to be clear, they way you @ama-gi have communicated so-far does not make me feel, there is a need to respect you. And that's OK, by that I am excluding you and everything you could have offered to me. That's my loss, but at the same time you are loosing what I could have offered you! See were am I going here? If you think it's OK, to say whatever you have on your mind, go for it. Be yourself, but know that by behaving like this your actions will have consequences that will alienate people who do not agree with this way of acting.

I made a choice to say and do things a certain way, to be kind and respectful and to consider people of other groups including the LGBTQIA community, and there "unconventional" ways. Do I agree with everything? Not necessarily, but I do respect them as long as they respect me.

> The notion that community members should modify their speech so as not to insult an oversensitive person is ridiculous. People that feel personally hurt by criticism can't work together with other people.

We choose our words, we choose who we want to be, if I choose to be a jerk to other people who are different I am only portraying how I expect them to thread me. If we _all_ acted like this we will end-up alone, our pride (which is considered a sin for reason) will be the death of us. If we can choose to be like this, then we can also choose to be more kind and inclusive to others opinions and believes.

That's what the whole diversity initiative is about! Creating a more diverse demographic of developers, so we can all benefit. There countless of examples were diversity and creating a more welcoming community/environment has resulted in some incredible result ❤️

But these are only opinions, you are free disagree with them. If you can provide other arguments or I if misunderstood some of your reasoning I willing to change my opinion on this topic.

**And to the others who have replied so far, this is a great example on how to have a respectful and constructive conversation. Keeping your calm on this topic, while being very passionate about this topic. ❤️ You people rock 🤘**
