### ISSUE TITLE
information signs for the CoC at events

### ISSUE THREAD

**Issue by lsmith77** [symfony/diversity#38]
this is the current sign used at SymfonyCon 2018

![3ab52a3b-8986-4fd0-8c2b-2f646aaab203](https://user-images.githubusercontent.com/300279/49577700-e67ce200-f93f-11e8-865c-56d8c57aab8b.jpeg)

a few suggestions for improvements:
* use care@symfony.com instead of coc@symfony.com
* remove the emoticon
* provide a link (and QR code) to the CoC and reporting process
* find an alternative phrasing to “not allowed”

**Comment by iltar** [comment]
_"To ensure a wonderful experience for all visitors, please keep the code of conduct in mind. You can contact the CARE team if you believe intervention is required."_

Not 100% sure of the wording, but it sounds a lot less policing like this.

The emoticons make it feel less serious, which I dislike as the issue is really serious. I agree on the `care` instead of `coc` email and the QR. However, if something happened to me, I'd rather flee the building than find this sign. I might also notice something far away from the sign or want to report it back at my hotel room or any other place quiet. At moments like that, I think it's important to (A) give quick access to the URL/Email and (B) have the QR code with you in the lanyard.

**Comment by TimoBakx** [comment]
Maybe a "_You can contact the CARE team for any assistance or questions._"? Required intervention sounds a bit harsh to me.

**Comment by iltar** [comment]
That sounds a lot better indeed!

**Comment by zanbaldwin** [comment]
> use care@symfony.com instead of coc@symfony.com

I heard either Anne-Sophie or Emilie literally say coc@symfony.com instead of “see-oh-see” at the opening speech, which is probably fine in French but probably not the best thing to say at an English-speaking conference 😛

**Comment by lsmith77** [comment]
@michellesanver already discussed this with Emilie.
