### ISSUE TITLE
create guidelines for how to do reviews

### ISSUE THREAD

**Issue by lsmith77** [symfony/diversity#4]
Right now we focus mostly on the technical aspects in our contribution documentation but it might make sense to also work on how we interact with contributors to make the experience more positive. There are already some other such initiatives on this topic we can learn from.

Here are some links related to this topic:
* http://sage.thesharps.us/2014/09/01/the-gentle-art-of-patch-review/
* http://dobegin.com/micromanagement-code-reviews/
* https://github.com/thoughtbot/guides/tree/master/code-review

**Comment by egircys** [comment]
This would be really helpful! Maybe it could be shaped similar to https://github.com/blog/1943-how-to-write-the-perfect-pull-request? I see the code review as giving and receiving feedback, so both sides would need to have some guidance.

**Comment by sstok** [comment]
I have some idea's, I will take note of some of idea's and will try to workout a draft 😛

- Being respectful towards differing opinions (arguments, facts, resources)
- Giving positive feedback (Your idea is good but _needs_ use some work)
- Explaining reasons for a bad practice (aka. "This is a bad idea". I personally fell for this trap to many times now 😯  )
- Knowing when take a step back (_don't get into flame wars or trying to force your opinion on others._ see first points about being respectful )
- _It's about the code not the people_ - a bug in the code doesn't make you a bad developer (encouragements in advance, in case you get a negative review/lots of comments).
- Asking for clarification (can take some examples the Thoughtbot code-review guide)
- Tone of voice (don't be formal or force yourself to write error free, "don't" swear or curse, feel free to make respectful "jokes" but nothing offensive)

**Comment by javiereguiluz** [comment]
@sstok just for your consideration: maybe you could also contact to ask for feedback to the people who have been making most of the code and docs reviews on Symfony repos during the last years. Thanks!

**Comment by dbu** [comment]
good points!

gathering feedback on the guidelines from the main reviewers sounds like a good idea. in the end, the guidelines only work if those people can agree to them - if they chose to ignore them, nothing is won. 

another consideration could be to add something that these guidelines are not about making compromises on the quality of code that gets merged in the end. the standards for the code can remain the same, but the way people get feedback can be more welcoming.

i guess one thing to discuss is how short feedback can be. i feel that sometimes, its very compact but neutral. new contributors might feel put off by that, while more regular contributors don't mind. and asking reviewers to write long texts each time could be asking too much... having some prepared snippets that explain the symfony process could be helpful. for example for when a PR has no tests, or is considered out of scope and won't be merged. explaining a bit of background on OS (by merging, the maintainers commit to maintain that code "forever" etc etc) makes sense - if we have prepared snippets, reviewers can employ those instead of either having to write something again each time or not talking about it.

**Comment by sstok** [comment]
@javiereguiluz Definitely on my _list_ 😉 your encouraging comments are my main inspiration 😄

**Comment by sstok** [comment]
Where can share/place _my_ (draft) work?

**Comment by javiereguiluz** [comment]
@sstok maybe submit a pull request to create a `doc/` or `resources/doc/` directory in this repo and store the guidelines there?

**Comment by lsmith77** [comment]
there is also a wiki on this repo ..
that being said, I guess in the end this will go into the symfony-docs anyway?

**Comment by sstok** [comment]
https://github.com/symfony/diversity/wiki/Giving-constructive-criticism 👍

**Comment by javiereguiluz** [comment]
@sstok thanks for publishing the draft. Sadly, since this is a wiki page and not a pull request, we can't contribute comments about specific lines and contents.

**Comment by sstok** [comment]
I will open a pull-request for symfony-docs 👍

**Comment by sstok** [comment]
See https://github.com/symfony/symfony-docs/pull/9034

**Comment by lsmith77** [comment]
done! w00p!!!!

**Comment by iltar** [comment]
For references: https://symfony.com/doc/current/contributing/community/review-comments
