### ISSUE TITLE
improving the support on our support channels

### ISSUE THREAD

**Issue by lsmith77** [symfony/diversity#40]
maybe this should get separate tickets but places like the #support slack channel, stackoverflow and github issues are the place a lot of beginners rely upon for their first steps. however due to their lack of experience they tend to ask questions that experienced people might think is “just lazy” so they down vote etc. So we should provide some level of coaching for people to better handle those types of questions.

Also questions get answered over and over .. we should make sure that questions get persisted (especially those from slack), by encouraging people to either add those things to the docs (here often to issue seems to be people do not know where in the docs or are afraid they do not write good enough english) ..

**Comment by Nyholm** [comment]
#SymfonyConHackDay2018

**Comment by zanbaldwin** [comment]
It might help to normalise Stack Overflow. One idea that floated around was to write a Slack bot that posts new #symfony questions from Stack Overflow into the support channel: (a) there’s history with SO unlike Slack, and (b) it would encourage new people coming to the support channel to post questions on SO instead of repeating questions that get erased by Slack.

Also, when someone joins Slack they should automatically be added to the support channel to reduce the amount of people posting support questions in the general channel.

**Comment by TimoBakx** [comment]
I agree. And maybe there's a way to make it easier to open an issue in the symfony/docs repository? I have a feeling that most of the underdocumented issues are caused by people not knowing that things should be documented or that some documentation might need improving.

Opening a ticket like "I read this page and this part doesn't make sense to me, please contact me [insert Slack/Twitter handle] to discuss." would probably help.

**Comment by zanbaldwin** [comment]
This would also add the opportunity of getting metrics (which we can’t do on slack) - common questions or high traffic questions could be sent to the docs team for them to consider adding to the docs (or making it less hard to find).

**Comment by lsmith77** [comment]
next step is @dbrumann doing a blog post to try and reach out to all the SO involved people in the Symfony community.

possibly strategies:
* get SO to have better tools for moderators to focus on specific tags and then build a closer relationship to moderators working on Symfony related tags
* convince SO to give us our own sub-SO (they seem to give them to apps like Drupal, Magento ..)

setting up our own alternative system seems like a high effort, high risk option, so we should really exhaust all options to collaborate with SO.

**Comment by lsmith77** [comment]
the issues with current SO:

* karma system requires collecting points to be able to actually help
* accepted answers can not be easily be updated if there are relevant changes in Symfony
* our CARE process cannot be applied

**Comment by lsmith77** [comment]
closing for now .. its not feasible to setup our own infrastructure. SO isn't giving us our own space. Denis did the blog post.
