### ISSUE TITLE
Add a speaking workshop to the SymfonyCon workshops

### ISSUE THREAD

**Issue by TimoBakx** [symfony/diversity#55]
As far as I can see, the workshops at Lisbon were mostly technical. Perhaps we could include a webshop about speaking (including mentoring)?

#SymfonyConHackDay2018

**Comment by Nyholm** [comment]
I think this is a good idea. 
Though note: I've been to a conference where they did that and we had a small issue. Since the workshops are before the talks (on the conference page), people that wanted to review my talk accidentally reviewed my workshop. 

A solution could be to add a "workshop conference" and the normal conference in Joind.in. One could also fake the date of the workshops so they appear after the normal talks.

**Comment by TimoBakx** [comment]
I think separating the workshops and the conference talks in Joind.in is a good idea. It's less confusing that way and people that get conference-only tickets also have less overhead.

**Comment by dbu** [comment]
workshops usually are payed extra and before the actual conference. do you mean to offer a workshop that would cost extra for the participants? it could be a try but i am not sure if it will reach the people that would need such a workshop. i might be wrong, no idea if other conferences tried it and had success.

maybe a first talk session on the first day could be about doing talks and such, to promote the unconf more?

**Comment by michellesanver** [comment]
EU Fossa hackathon: Next step; Propose that the lightning talk track starts with a presentation about how to do a presentation. 10 - 20 minutes. Focus less on slide design but more about delivery.

**Comment by michellesanver** [comment]
Next step: Talk to @Nyholm and @nicolas-grekas about possibly doing this presentation (talk to them during EU FOSSA Hackathon.) 

For content this could help with inspiration: https://www.globaldiversitycfpday.com/schedule

**Comment by lsmith77** [comment]
closing in favor of https://github.com/symfony/diversity/issues/98
