### ISSUE TITLE
[discussion] How could we improve the setting of the Conference Social?

### ISSUE THREAD

**Issue by TimoBakx** [symfony/diversity#60]
Putting everyone in a room with loud music and alcohol might not be the best way to promote networking and discussions.

Some alternative ideas:
- Board game evening
- Tables with topics in a setting with food and/or drinks.

#SymfonyConHackDay2018

**Comment by iltar** [comment]
Another alternative might be retrospective-like games to interact, perhaps with small groups in an exercise that lasts maybe 15 minutes max? Could be a great way to connect

**Comment by zanbaldwin** [comment]
(Copied from #59)

Putting everyone into a room/venue, supplying alcohol, and expecting people to just get on with it excludes a fair few people. Other social events (not just in the evening) should be provided as alternatives (or even better, additional).

One idea from today was to have a speed-dating style discussion room. 5 minutes to talk about Symfony, PHP or other related topics at a time before moving onto the next person.
Another was board games.
Other ideas welcome!

The main theme however was that people need a common theme, topic, joint activity, etc to assist with social cohesion (rather than relying on alcohol to feel comfortable enough speaking with strangers).

#SymfonyConHackday2018

**Comment by nicolas-grekas** [comment]
Note that the hackday is providing exactly this to me.

**Comment by TimoBakx** [comment]
The hackday is nice for this, but I think the boundary to join might be a bit high. It's an extra day (so perhaps an extra night in the hotel) and perhaps the whole "am I good enough of a dev to attend the hack day"?

**Comment by michellesanver** [comment]
Discussed at EU Fossa Hackathon. Shared in Diversity on Slack, Lukas has the link if it disappears... ;)
