### ISSUE TITLE
how to collect donations

### ISSUE THREAD

**Issue by lsmith77** [symfony/diversity#66]
for now we have opencollective.com 

they provide a nice UI, tools for managing budgets and handle the accounting and legal status. more importantly they allow us to manage those funds separate of Symfony corp which helps avoid confusion (am I donating to a company?) and also clearifies the funds being owned by a “not for profit” open source project.

however there are some concerns that @nicolas-grekas outlined to me

> opencollective vs SFCorp as fiscal sponsor
> 
> Right now opencollective provides the legal status for gathering the funds. This has several significant drawbacks:
> 
> * they take 5% for this - which adds to the 5% they already take for providing the service + 3% stripes takes
> * money must be spent before it is reimbursed (by sending them the invoices) - this doesn't work with scholarships so SFCorp had to advance the money for SFCon
> * they reimburse the money using Paypal and in USD only - which imposes additional fees and doesn't work with ppl that don't have a paypal account.
> 
> For all these reasons combined, we worked with opencollective and were about to swap the fiscal sponsor - something they allow. We did full stop yesterday when we realized this might not be your recommendation and we should first solve this question together. Our idea was to setup things this way:
> 
> * save the extra 5% by managing the funds directly
> * create a dedicated stripe account where the money goes directly
> * pay the expenses using that stripe account - using virtual credit cards in the near future when stripe will release the feature - and without requiring anyone to advance any funds
> * have SFCorp employees do the pre-expenses work (select flight, book hotel, etc)

now as stated above Symfony corp will not act on their own here. they want to help and are willing to do as much as managing everything (see above) or as little as simply having opencollective.com do all the work or anything in between. we just need to figure out what is the best for the community.

one note about advancing funds. I think we will also want to do donation drives in the future. but these will either need to be sufficiently in advance so that the funds have been paid to us already or have enough funds to pre-allocate money and simply use the donation drive to see if similar budgets should be granted in the future.

**Comment by nicolas-grekas** [comment]
Oh something I didn't mention: a company told me they won't give money because the money transits via the US and that's against their policies.

**Comment by zanbaldwin** [comment]
:point_up: I think keeping money within the EU will be a wise move - it's definitely something that needs to be taken into consideration at least.

**Comment by bobdenotter** [comment]
I'm no expert by any means, but if there's a money/personally-identifiable information flow, keeping it in the EU would also mean less hassle on our side, GDPR-wise.

**Comment by dbu** [comment]
important point about this initiative paying the expenses in advance rather than asking the sponsored people to forward the money and reimburse them. for some, forwarding the money will be okay, but others might not have the money around to wait a month or two on 500 Euro...

and burning 10% on the donations on fees indeed feels quite sad.

**Comment by lsmith77** [comment]
to me the 10% for making sure we do not have to deal with accounting and legal status is worth it. but we need to be as accomodating as possible when we do pay outs which to me is currently the killer for opencollective.com

**Comment by xdamman** [comment]
Hi everyone. Xavier here from open collective. Merry Xmas! :-)

We also have a fiscal sponsor based in Brussels so we could move you there if most of your donations/expenses are in euros.

We can also do payouts by bank transfer to IBAN numbers from our European host. But since it’s still a manual process for us, this also costs a fee (similar to PayPal to keep things even). You can also ask vendors to directly file their invoices to your collective so that you don’t have to advance the money (but doesn’t work for flights indeed).

> pay the expenses using that stripe account - using virtual credit cards in the near future when stripe will release the feature - and without requiring anyone to advance any funds

Instead of building this feature just for you why not working together to implement it on open collective (which is open source mit license) so that all open source projects could benefit from it? This would be an awesome addition. 

The point is that those issues are far from being specific to the symfony community. We would love to solve those problems for all. It’s much easier to mutualize accounting and legal between multiple communities than having everyone figure those things out for themselves and revintening the wheel every single time. Believe me you don’t want to get into European VAT nightmare. It’s a bit like if everyone had to figure out how to compile Linux and Apache to have their own blog. We can have one server and share it between many websites. 

So if you are up for it, we can work together to improve those points to not only make it easier for you but for many others as well in the process. The entire open source community will greatly benefit!

**Comment by lsmith77** [comment]
@xdamman thanks for responding so quickly (FYI I reached out to them only today).

Did you already initiate a switch to a different host? It seems like we are currently not accepting donations and in the admin I currently see:
```
You have applied to be hosted by Open Source Collective 501c6 (Non Profit) on Invalid Date. Your application is being reviewed. As soon as the host accepts, you will be able to start collecting money for your collective.
```

**Comment by xdamman** [comment]
I haven’t done anything. But it looks like you asked to switch host and then got back on your decision? You want to be hosted again on the open source collective 501c6 in the US? (https://opencollective.com/opensource) I haven’t followed your case. @piamancini did and can probably help here.

**Comment by lsmith77** [comment]
OK thx .. will check with the other admins to try and figure out what is going on.

**Comment by piamancini** [comment]
Hi all, 

Yes Louise from Symfony reached out and asked to move to their organization in EU, so fees would be lower and the collective would be in EUROS. In order to do this, they needed to vacate all the collective's budget and change hosts. We did this (they submitted an expense and we send them all the funds) they now need to connect the new host which they haven't done yet. 

Ideally they'll switch to the new host before the 1st of the month, otherwise all the donations are going to be sent again to the 501c6.

**Comment by piamancini** [comment]
correction: it looks like they removed the 501c6 host but haven't connected the new stripe account yet. This can be done in opencollective.com/symfony/edit/host

**Comment by alannallama** [comment]
[Here is an open issue](https://github.com/opencollective/opencollective/issues/1429) regarding adding payment via Stripe direct to bank accounts to the Open Collective system. I agree that this would be great to offer all our users, as some people don't want to use Paypal.

**Comment by xdamman** [comment]
You have 6 active yearly donations for a total of $3,000/year and 13 active donations for a total of $116/month. Monthly donations are run on the first of the month. Yearly donations are run on the first of the same month of the first donation ([code](https://github.com/OpenCollective/opencollective-api/blob/93823f81e321d4250b0792a601453a530669c95f/server/lib/subscriptions.js#L159-L160)).
We can't move over those subscriptions to a different currency (people expect to pay a given amount in a given currency).
What we can do is move your collective https://opencollective.com/symfony to `/symfony-usd` and create a new one `/symfony` which will be hosted on the European Host.
That will make things clear. 
Eventually our goal is to allow collectives to have more than one host so that individual backers can choose to give money to a personal stripe account and only have 5% fee for open collective, and companies can give to a fiscal sponsor to make sure they have a proper invoice and pay an extra host fee. That will also make it possible to support multiple currencies (and crypto wallets!). So exciting things ahead but we are not there yet!
So in the meantime, as a hack you can have two collectives and we can make the usd one show up as a project of the new primary one /symfony – how does that sound?
In the same way, you could have a 3rd collective for `/symfony-scholarships` hosted by your company.

**Comment by lsmith77** [comment]
@xdamman

**Comment by lsmith77** [comment]
is there a ticket already for stripe virtual credit cards (
https://stripe.com/issuing) as a payout option?

**Comment by lsmith77** [comment]
created one here https://github.com/opencollective/opencollective/issues/1603

**Comment by lsmith77** [comment]
at the last meeting we made a decision https://github.com/symfony/diversity/wiki/Thu-3rd-2019

1) we rename the current collective from “symfony” to “symfony-usd”
2) we create a new “symfony” collective using the opencollective provided EU based fiscal host (ie. not Symfony corp to not loose the non profit status)
3) we create dedicated cause specific sub-collectives where we usually only collect one time donations (left over money goes to “symfony”) and missing funds for the cause can get filled up by money from “symfony” and “symfony-usd”
